//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 
namespace PositioningControlNs
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "PositioningControl", Namespace = "urn:schemas-pelco-com:service:PositioningControl:1")]
    public partial class PositioningControl : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback EnableSpeedProfileOperationCompleted;

        private System.Threading.SendOrPostCallback RestoreDefaultSpeedProfileOperationCompleted;

        private System.Threading.SendOrPostCallback RestoreDefaultPositionLimitsOperationCompleted;

        private System.Threading.SendOrPostCallback GetSpeedProfileOperationCompleted;

        private System.Threading.SendOrPostCallback GetAllSpeedProfilesOperationCompleted;

        private System.Threading.SendOrPostCallback GetEnabledSpeedProfileOperationCompleted;

        private System.Threading.SendOrPostCallback GetAzimuthZeroOperationCompleted;

        private System.Threading.SendOrPostCallback GetPositionOperationCompleted;

        private System.Threading.SendOrPostCallback GetPositionEventIntervalOperationCompleted;

        private System.Threading.SendOrPostCallback GetPositionLimitsOperationCompleted;

        private System.Threading.SendOrPostCallback GetVelocityOperationCompleted;

        private System.Threading.SendOrPostCallback GetVelocityLimitsOperationCompleted;

        private System.Threading.SendOrPostCallback GetVelocityURLOperationCompleted;

        private System.Threading.SendOrPostCallback InitializePositionOperationCompleted;

        private System.Threading.SendOrPostCallback SetAzimuthZeroOperationCompleted;

        private System.Threading.SendOrPostCallback SetPositionOperationCompleted;

        private System.Threading.SendOrPostCallback SetPositionEventIntervalOperationCompleted;

        private System.Threading.SendOrPostCallback SetVelocityOperationCompleted;

        private System.Threading.SendOrPostCallback ViewObjectOperationCompleted;

        /// <remarks/>
        public PositioningControl()
        {
            this.Url = "http://localhost:49152/control/PositioningControl-1";
        }

        /// <remarks/>
        public event EnableSpeedProfileCompletedEventHandler EnableSpeedProfileCompleted;

        /// <remarks/>
        public event RestoreDefaultSpeedProfileCompletedEventHandler RestoreDefaultSpeedProfileCompleted;

        /// <remarks/>
        public event RestoreDefaultPositionLimitsCompletedEventHandler RestoreDefaultPositionLimitsCompleted;

        /// <remarks/>
        public event GetSpeedProfileCompletedEventHandler GetSpeedProfileCompleted;

        /// <remarks/>
        public event GetAllSpeedProfilesCompletedEventHandler GetAllSpeedProfilesCompleted;

        /// <remarks/>
        public event GetEnabledSpeedProfileCompletedEventHandler GetEnabledSpeedProfileCompleted;

        /// <remarks/>
        public event GetAzimuthZeroCompletedEventHandler GetAzimuthZeroCompleted;

        /// <remarks/>
        public event GetPositionCompletedEventHandler GetPositionCompleted;

        /// <remarks/>
        public event GetPositionEventIntervalCompletedEventHandler GetPositionEventIntervalCompleted;

        /// <remarks/>
        public event GetPositionLimitsCompletedEventHandler GetPositionLimitsCompleted;

        /// <remarks/>
        public event GetVelocityCompletedEventHandler GetVelocityCompleted;

        /// <remarks/>
        public event GetVelocityLimitsCompletedEventHandler GetVelocityLimitsCompleted;

        /// <remarks/>
        public event GetVelocityURLCompletedEventHandler GetVelocityURLCompleted;

        /// <remarks/>
        public event InitializePositionCompletedEventHandler InitializePositionCompleted;

        /// <remarks/>
        public event SetAzimuthZeroCompletedEventHandler SetAzimuthZeroCompleted;

        /// <remarks/>
        public event SetPositionCompletedEventHandler SetPositionCompleted;

        /// <remarks/>
        public event SetPositionEventIntervalCompletedEventHandler SetPositionEventIntervalCompleted;

        /// <remarks/>
        public event SetVelocityCompletedEventHandler SetVelocityCompleted;

        /// <remarks/>
        public event ViewObjectCompletedEventHandler ViewObjectCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#EnableSpeedProfile", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnableSpeedProfile([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string ProfileId)
        {
            this.Invoke("EnableSpeedProfile", new object[] {
                        ProfileId});
        }

        /// <remarks/>
        public System.IAsyncResult BeginEnableSpeedProfile(string ProfileId, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EnableSpeedProfile", new object[] {
                        ProfileId}, callback, asyncState);
        }

        /// <remarks/>
        public void EndEnableSpeedProfile(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void EnableSpeedProfileAsync(string ProfileId)
        {
            this.EnableSpeedProfileAsync(ProfileId, null);
        }

        /// <remarks/>
        public void EnableSpeedProfileAsync(string ProfileId, object userState)
        {
            if ((this.EnableSpeedProfileOperationCompleted == null))
            {
                this.EnableSpeedProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnableSpeedProfileOperationCompleted);
            }
            this.InvokeAsync("EnableSpeedProfile", new object[] {
                        ProfileId}, this.EnableSpeedProfileOperationCompleted, userState);
        }

        private void OnEnableSpeedProfileOperationCompleted(object arg)
        {
            if ((this.EnableSpeedProfileCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnableSpeedProfileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#RestoreDefaultSpeedProfile", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RestoreDefaultSpeedProfile()
        {
            this.Invoke("RestoreDefaultSpeedProfile", new object[0]);
        }

        /// <remarks/>
        public System.IAsyncResult BeginRestoreDefaultSpeedProfile(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("RestoreDefaultSpeedProfile", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public void EndRestoreDefaultSpeedProfile(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void RestoreDefaultSpeedProfileAsync()
        {
            this.RestoreDefaultSpeedProfileAsync(null);
        }

        /// <remarks/>
        public void RestoreDefaultSpeedProfileAsync(object userState)
        {
            if ((this.RestoreDefaultSpeedProfileOperationCompleted == null))
            {
                this.RestoreDefaultSpeedProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRestoreDefaultSpeedProfileOperationCompleted);
            }
            this.InvokeAsync("RestoreDefaultSpeedProfile", new object[0], this.RestoreDefaultSpeedProfileOperationCompleted, userState);
        }

        private void OnRestoreDefaultSpeedProfileOperationCompleted(object arg)
        {
            if ((this.RestoreDefaultSpeedProfileCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RestoreDefaultSpeedProfileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#RestoreDefaultPositionLimits", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RestoreDefaultPositionLimits()
        {
            this.Invoke("RestoreDefaultPositionLimits", new object[0]);
        }

        /// <remarks/>
        public System.IAsyncResult BeginRestoreDefaultPositionLimits(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("RestoreDefaultPositionLimits", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public void EndRestoreDefaultPositionLimits(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void RestoreDefaultPositionLimitsAsync()
        {
            this.RestoreDefaultPositionLimitsAsync(null);
        }

        /// <remarks/>
        public void RestoreDefaultPositionLimitsAsync(object userState)
        {
            if ((this.RestoreDefaultPositionLimitsOperationCompleted == null))
            {
                this.RestoreDefaultPositionLimitsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRestoreDefaultPositionLimitsOperationCompleted);
            }
            this.InvokeAsync("RestoreDefaultPositionLimits", new object[0], this.RestoreDefaultPositionLimitsOperationCompleted, userState);
        }

        private void OnRestoreDefaultPositionLimitsOperationCompleted(object arg)
        {
            if ((this.RestoreDefaultPositionLimitsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RestoreDefaultPositionLimitsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#GetSpeedProfile", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SpeedProfile", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpeedProfile GetSpeedProfile([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string ProfileId)
        {
            object[] results = this.Invoke("GetSpeedProfile", new object[] {
                        ProfileId});
            return ((SpeedProfile)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetSpeedProfile(string ProfileId, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetSpeedProfile", new object[] {
                        ProfileId}, callback, asyncState);
        }

        /// <remarks/>
        public SpeedProfile EndGetSpeedProfile(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((SpeedProfile)(results[0]));
        }

        /// <remarks/>
        public void GetSpeedProfileAsync(string ProfileId)
        {
            this.GetSpeedProfileAsync(ProfileId, null);
        }

        /// <remarks/>
        public void GetSpeedProfileAsync(string ProfileId, object userState)
        {
            if ((this.GetSpeedProfileOperationCompleted == null))
            {
                this.GetSpeedProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSpeedProfileOperationCompleted);
            }
            this.InvokeAsync("GetSpeedProfile", new object[] {
                        ProfileId}, this.GetSpeedProfileOperationCompleted, userState);
        }

        private void OnGetSpeedProfileOperationCompleted(object arg)
        {
            if ((this.GetSpeedProfileCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSpeedProfileCompleted(this, new GetSpeedProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#GetAllSpeedProfiles", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SpeedProfile", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpeedProfile[] GetAllSpeedProfiles()
        {
            object[] results = this.Invoke("GetAllSpeedProfiles", new object[0]);
            return ((SpeedProfile[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAllSpeedProfiles(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAllSpeedProfiles", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public SpeedProfile[] EndGetAllSpeedProfiles(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((SpeedProfile[])(results[0]));
        }

        /// <remarks/>
        public void GetAllSpeedProfilesAsync()
        {
            this.GetAllSpeedProfilesAsync(null);
        }

        /// <remarks/>
        public void GetAllSpeedProfilesAsync(object userState)
        {
            if ((this.GetAllSpeedProfilesOperationCompleted == null))
            {
                this.GetAllSpeedProfilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllSpeedProfilesOperationCompleted);
            }
            this.InvokeAsync("GetAllSpeedProfiles", new object[0], this.GetAllSpeedProfilesOperationCompleted, userState);
        }

        private void OnGetAllSpeedProfilesOperationCompleted(object arg)
        {
            if ((this.GetAllSpeedProfilesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllSpeedProfilesCompleted(this, new GetAllSpeedProfilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#GetEnabledSpeedProfile", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("EnabledSpeedProfile", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpeedProfile GetEnabledSpeedProfile()
        {
            object[] results = this.Invoke("GetEnabledSpeedProfile", new object[0]);
            return ((SpeedProfile)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetEnabledSpeedProfile(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetEnabledSpeedProfile", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public SpeedProfile EndGetEnabledSpeedProfile(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((SpeedProfile)(results[0]));
        }

        /// <remarks/>
        public void GetEnabledSpeedProfileAsync()
        {
            this.GetEnabledSpeedProfileAsync(null);
        }

        /// <remarks/>
        public void GetEnabledSpeedProfileAsync(object userState)
        {
            if ((this.GetEnabledSpeedProfileOperationCompleted == null))
            {
                this.GetEnabledSpeedProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEnabledSpeedProfileOperationCompleted);
            }
            this.InvokeAsync("GetEnabledSpeedProfile", new object[0], this.GetEnabledSpeedProfileOperationCompleted, userState);
        }

        private void OnGetEnabledSpeedProfileOperationCompleted(object arg)
        {
            if ((this.GetEnabledSpeedProfileCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEnabledSpeedProfileCompleted(this, new GetEnabledSpeedProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#GetAzimuthZero", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("AzimuthZero", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int GetAzimuthZero()
        {
            object[] results = this.Invoke("GetAzimuthZero", new object[0]);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAzimuthZero(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAzimuthZero", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public int EndGetAzimuthZero(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public void GetAzimuthZeroAsync()
        {
            this.GetAzimuthZeroAsync(null);
        }

        /// <remarks/>
        public void GetAzimuthZeroAsync(object userState)
        {
            if ((this.GetAzimuthZeroOperationCompleted == null))
            {
                this.GetAzimuthZeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAzimuthZeroOperationCompleted);
            }
            this.InvokeAsync("GetAzimuthZero", new object[0], this.GetAzimuthZeroOperationCompleted, userState);
        }

        private void OnGetAzimuthZeroOperationCompleted(object arg)
        {
            if ((this.GetAzimuthZeroCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAzimuthZeroCompleted(this, new GetAzimuthZeroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#GetPosition", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("position", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Velocity GetPosition()
        {
            object[] results = this.Invoke("GetPosition", new object[0]);
            return ((Velocity)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetPosition(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetPosition", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public Velocity EndGetPosition(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Velocity)(results[0]));
        }

        /// <remarks/>
        public void GetPositionAsync()
        {
            this.GetPositionAsync(null);
        }

        /// <remarks/>
        public void GetPositionAsync(object userState)
        {
            if ((this.GetPositionOperationCompleted == null))
            {
                this.GetPositionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPositionOperationCompleted);
            }
            this.InvokeAsync("GetPosition", new object[0], this.GetPositionOperationCompleted, userState);
        }

        private void OnGetPositionOperationCompleted(object arg)
        {
            if ((this.GetPositionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPositionCompleted(this, new GetPositionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#GetPositionEventInterval", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("positionEventInterval", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GetPositionEventInterval()
        {
            object[] results = this.Invoke("GetPositionEventInterval", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetPositionEventInterval(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetPositionEventInterval", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndGetPositionEventInterval(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetPositionEventIntervalAsync()
        {
            this.GetPositionEventIntervalAsync(null);
        }

        /// <remarks/>
        public void GetPositionEventIntervalAsync(object userState)
        {
            if ((this.GetPositionEventIntervalOperationCompleted == null))
            {
                this.GetPositionEventIntervalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPositionEventIntervalOperationCompleted);
            }
            this.InvokeAsync("GetPositionEventInterval", new object[0], this.GetPositionEventIntervalOperationCompleted, userState);
        }

        private void OnGetPositionEventIntervalOperationCompleted(object arg)
        {
            if ((this.GetPositionEventIntervalCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPositionEventIntervalCompleted(this, new GetPositionEventIntervalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#GetPositionLimits", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("positionLimits", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AxisLimits GetPositionLimits()
        {
            object[] results = this.Invoke("GetPositionLimits", new object[0]);
            return ((AxisLimits)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetPositionLimits(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetPositionLimits", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public AxisLimits EndGetPositionLimits(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((AxisLimits)(results[0]));
        }

        /// <remarks/>
        public void GetPositionLimitsAsync()
        {
            this.GetPositionLimitsAsync(null);
        }

        /// <remarks/>
        public void GetPositionLimitsAsync(object userState)
        {
            if ((this.GetPositionLimitsOperationCompleted == null))
            {
                this.GetPositionLimitsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPositionLimitsOperationCompleted);
            }
            this.InvokeAsync("GetPositionLimits", new object[0], this.GetPositionLimitsOperationCompleted, userState);
        }

        private void OnGetPositionLimitsOperationCompleted(object arg)
        {
            if ((this.GetPositionLimitsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPositionLimitsCompleted(this, new GetPositionLimitsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#GetVelocity", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("velocity", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Velocity GetVelocity()
        {
            object[] results = this.Invoke("GetVelocity", new object[0]);
            return ((Velocity)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetVelocity(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetVelocity", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public Velocity EndGetVelocity(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Velocity)(results[0]));
        }

        /// <remarks/>
        public void GetVelocityAsync()
        {
            this.GetVelocityAsync(null);
        }

        /// <remarks/>
        public void GetVelocityAsync(object userState)
        {
            if ((this.GetVelocityOperationCompleted == null))
            {
                this.GetVelocityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVelocityOperationCompleted);
            }
            this.InvokeAsync("GetVelocity", new object[0], this.GetVelocityOperationCompleted, userState);
        }

        private void OnGetVelocityOperationCompleted(object arg)
        {
            if ((this.GetVelocityCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVelocityCompleted(this, new GetVelocityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#GetVelocityLimits", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("velocityLimits", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VelocityLimits GetVelocityLimits()
        {
            object[] results = this.Invoke("GetVelocityLimits", new object[0]);
            return ((VelocityLimits)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetVelocityLimits(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetVelocityLimits", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public VelocityLimits EndGetVelocityLimits(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((VelocityLimits)(results[0]));
        }

        /// <remarks/>
        public void GetVelocityLimitsAsync()
        {
            this.GetVelocityLimitsAsync(null);
        }

        /// <remarks/>
        public void GetVelocityLimitsAsync(object userState)
        {
            if ((this.GetVelocityLimitsOperationCompleted == null))
            {
                this.GetVelocityLimitsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVelocityLimitsOperationCompleted);
            }
            this.InvokeAsync("GetVelocityLimits", new object[0], this.GetVelocityLimitsOperationCompleted, userState);
        }

        private void OnGetVelocityLimitsOperationCompleted(object arg)
        {
            if ((this.GetVelocityLimitsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVelocityLimitsCompleted(this, new GetVelocityLimitsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#GetVelocityURL", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("velocityURL", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GetVelocityURL()
        {
            object[] results = this.Invoke("GetVelocityURL", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetVelocityURL(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetVelocityURL", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndGetVelocityURL(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetVelocityURLAsync()
        {
            this.GetVelocityURLAsync(null);
        }

        /// <remarks/>
        public void GetVelocityURLAsync(object userState)
        {
            if ((this.GetVelocityURLOperationCompleted == null))
            {
                this.GetVelocityURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVelocityURLOperationCompleted);
            }
            this.InvokeAsync("GetVelocityURL", new object[0], this.GetVelocityURLOperationCompleted, userState);
        }

        private void OnGetVelocityURLOperationCompleted(object arg)
        {
            if ((this.GetVelocityURLCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVelocityURLCompleted(this, new GetVelocityURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#InitializePosition", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InitializePosition([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] Velocity position)
        {
            this.Invoke("InitializePosition", new object[] {
                        position});
        }

        /// <remarks/>
        public System.IAsyncResult BeginInitializePosition(Velocity position, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("InitializePosition", new object[] {
                        position}, callback, asyncState);
        }

        /// <remarks/>
        public void EndInitializePosition(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void InitializePositionAsync(Velocity position)
        {
            this.InitializePositionAsync(position, null);
        }

        /// <remarks/>
        public void InitializePositionAsync(Velocity position, object userState)
        {
            if ((this.InitializePositionOperationCompleted == null))
            {
                this.InitializePositionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializePositionOperationCompleted);
            }
            this.InvokeAsync("InitializePosition", new object[] {
                        position}, this.InitializePositionOperationCompleted, userState);
        }

        private void OnInitializePositionOperationCompleted(object arg)
        {
            if ((this.InitializePositionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializePositionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#SetAzimuthZero", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetAzimuthZero([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] int AzimuthZero)
        {
            this.Invoke("SetAzimuthZero", new object[] {
                        AzimuthZero});
        }

        /// <remarks/>
        public System.IAsyncResult BeginSetAzimuthZero(int AzimuthZero, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SetAzimuthZero", new object[] {
                        AzimuthZero}, callback, asyncState);
        }

        /// <remarks/>
        public void EndSetAzimuthZero(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void SetAzimuthZeroAsync(int AzimuthZero)
        {
            this.SetAzimuthZeroAsync(AzimuthZero, null);
        }

        /// <remarks/>
        public void SetAzimuthZeroAsync(int AzimuthZero, object userState)
        {
            if ((this.SetAzimuthZeroOperationCompleted == null))
            {
                this.SetAzimuthZeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetAzimuthZeroOperationCompleted);
            }
            this.InvokeAsync("SetAzimuthZero", new object[] {
                        AzimuthZero}, this.SetAzimuthZeroOperationCompleted, userState);
        }

        private void OnSetAzimuthZeroOperationCompleted(object arg)
        {
            if ((this.SetAzimuthZeroCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetAzimuthZeroCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#SetPosition", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetPosition([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] Velocity position)
        {
            this.Invoke("SetPosition", new object[] {
                        position});
        }

        /// <remarks/>
        public System.IAsyncResult BeginSetPosition(Velocity position, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SetPosition", new object[] {
                        position}, callback, asyncState);
        }

        /// <remarks/>
        public void EndSetPosition(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void SetPositionAsync(Velocity position)
        {
            this.SetPositionAsync(position, null);
        }

        /// <remarks/>
        public void SetPositionAsync(Velocity position, object userState)
        {
            if ((this.SetPositionOperationCompleted == null))
            {
                this.SetPositionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPositionOperationCompleted);
            }
            this.InvokeAsync("SetPosition", new object[] {
                        position}, this.SetPositionOperationCompleted, userState);
        }

        private void OnSetPositionOperationCompleted(object arg)
        {
            if ((this.SetPositionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPositionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#SetPositionEventInterval", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetPositionEventInterval([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string positionEventInterval)
        {
            this.Invoke("SetPositionEventInterval", new object[] {
                        positionEventInterval});
        }

        /// <remarks/>
        public System.IAsyncResult BeginSetPositionEventInterval(string positionEventInterval, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SetPositionEventInterval", new object[] {
                        positionEventInterval}, callback, asyncState);
        }

        /// <remarks/>
        public void EndSetPositionEventInterval(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void SetPositionEventIntervalAsync(string positionEventInterval)
        {
            this.SetPositionEventIntervalAsync(positionEventInterval, null);
        }

        /// <remarks/>
        public void SetPositionEventIntervalAsync(string positionEventInterval, object userState)
        {
            if ((this.SetPositionEventIntervalOperationCompleted == null))
            {
                this.SetPositionEventIntervalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPositionEventIntervalOperationCompleted);
            }
            this.InvokeAsync("SetPositionEventInterval", new object[] {
                        positionEventInterval}, this.SetPositionEventIntervalOperationCompleted, userState);
        }

        private void OnSetPositionEventIntervalOperationCompleted(object arg)
        {
            if ((this.SetPositionEventIntervalCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPositionEventIntervalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#SetVelocity", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetVelocity([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] Velocity velocity)
        {
            this.Invoke("SetVelocity", new object[] {
                        velocity});
        }

        /// <remarks/>
        public System.IAsyncResult BeginSetVelocity(Velocity velocity, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SetVelocity", new object[] {
                        velocity}, callback, asyncState);
        }

        /// <remarks/>
        public void EndSetVelocity(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void SetVelocityAsync(Velocity velocity)
        {
            this.SetVelocityAsync(velocity, null);
        }

        /// <remarks/>
        public void SetVelocityAsync(Velocity velocity, object userState)
        {
            if ((this.SetVelocityOperationCompleted == null))
            {
                this.SetVelocityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetVelocityOperationCompleted);
            }
            this.InvokeAsync("SetVelocity", new object[] {
                        velocity}, this.SetVelocityOperationCompleted, userState);
        }

        private void OnSetVelocityOperationCompleted(object arg)
        {
            if ((this.SetVelocityCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetVelocityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-pelco-com:service:PositioningControl:1#ViewObject", RequestNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", ResponseNamespace = "urn:schemas-pelco-com:service:PositioningControl:1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ViewObject([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] Velocity position, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] uint radius)
        {
            this.Invoke("ViewObject", new object[] {
                        position,
                        radius});
        }

        /// <remarks/>
        public System.IAsyncResult BeginViewObject(Velocity position, uint radius, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ViewObject", new object[] {
                        position,
                        radius}, callback, asyncState);
        }

        /// <remarks/>
        public void EndViewObject(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void ViewObjectAsync(Velocity position, uint radius)
        {
            this.ViewObjectAsync(position, radius, null);
        }

        /// <remarks/>
        public void ViewObjectAsync(Velocity position, uint radius, object userState)
        {
            if ((this.ViewObjectOperationCompleted == null))
            {
                this.ViewObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViewObjectOperationCompleted);
            }
            this.InvokeAsync("ViewObject", new object[] {
                        position,
                        radius}, this.ViewObjectOperationCompleted, userState);
        }

        private void OnViewObjectOperationCompleted(object arg)
        {
            if ((this.ViewObjectCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViewObjectCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-pelco-com:service:PositioningControl:1")]
    public partial class SpeedProfile
    {

        private string nameField;

        private VelocityLimits velocityLimitsField;

        private AccelerationLimits accelerationLimitsField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VelocityLimits VelocityLimits
        {
            get
            {
                return this.velocityLimitsField;
            }
            set
            {
                this.velocityLimitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AccelerationLimits AccelerationLimits
        {
            get
            {
                return this.accelerationLimitsField;
            }
            set
            {
                this.accelerationLimitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-pelco-com:service:PositioningControl:1")]
    public partial class VelocityLimits
    {

        private Xyzlimits translationField;

        private Xyzlimits rotationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public Xyzlimits translation
        {
            get
            {
                return this.translationField;
            }
            set
            {
                this.translationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public Xyzlimits rotation
        {
            get
            {
                return this.rotationField;
            }
            set
            {
                this.rotationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-pelco-com:service:PositioningControl:1")]
    public partial class Xyzlimits
    {

        private int xMinField;

        private bool xMinFieldSpecified;

        private int xMaxField;

        private bool xMaxFieldSpecified;

        private int yMinField;

        private bool yMinFieldSpecified;

        private int yMaxField;

        private bool yMaxFieldSpecified;

        private int zMinField;

        private bool zMinFieldSpecified;

        private int zMaxField;

        private bool zMaxFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int xMin
        {
            get
            {
                return this.xMinField;
            }
            set
            {
                this.xMinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xMinSpecified
        {
            get
            {
                return this.xMinFieldSpecified;
            }
            set
            {
                this.xMinFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int xMax
        {
            get
            {
                return this.xMaxField;
            }
            set
            {
                this.xMaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xMaxSpecified
        {
            get
            {
                return this.xMaxFieldSpecified;
            }
            set
            {
                this.xMaxFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int yMin
        {
            get
            {
                return this.yMinField;
            }
            set
            {
                this.yMinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yMinSpecified
        {
            get
            {
                return this.yMinFieldSpecified;
            }
            set
            {
                this.yMinFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int yMax
        {
            get
            {
                return this.yMaxField;
            }
            set
            {
                this.yMaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yMaxSpecified
        {
            get
            {
                return this.yMaxFieldSpecified;
            }
            set
            {
                this.yMaxFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int zMin
        {
            get
            {
                return this.zMinField;
            }
            set
            {
                this.zMinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zMinSpecified
        {
            get
            {
                return this.zMinFieldSpecified;
            }
            set
            {
                this.zMinFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int zMax
        {
            get
            {
                return this.zMaxField;
            }
            set
            {
                this.zMaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zMaxSpecified
        {
            get
            {
                return this.zMaxFieldSpecified;
            }
            set
            {
                this.zMaxFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-pelco-com:service:PositioningControl:1")]
    public partial class AxisLimits
    {

        private Xyzlimits translationField;

        private Xyzlimits rotationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public Xyzlimits translation
        {
            get
            {
                return this.translationField;
            }
            set
            {
                this.translationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public Xyzlimits rotation
        {
            get
            {
                return this.rotationField;
            }
            set
            {
                this.rotationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-pelco-com:service:PositioningControl:1")]
    public partial class Xyz
    {

        private int xField;

        private bool xFieldSpecified;

        private int yField;

        private bool yFieldSpecified;

        private int zField;

        private bool zFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xSpecified
        {
            get
            {
                return this.xFieldSpecified;
            }
            set
            {
                this.xFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ySpecified
        {
            get
            {
                return this.yFieldSpecified;
            }
            set
            {
                this.yFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int z
        {
            get
            {
                return this.zField;
            }
            set
            {
                this.zField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zSpecified
        {
            get
            {
                return this.zFieldSpecified;
            }
            set
            {
                this.zFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-pelco-com:service:PositioningControl:1")]
    public partial class Velocity
    {

        private Xyz translationField;

        private Xyz rotationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public Xyz translation
        {
            get
            {
                return this.translationField;
            }
            set
            {
                this.translationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public Xyz rotation
        {
            get
            {
                return this.rotationField;
            }
            set
            {
                this.rotationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-pelco-com:service:PositioningControl:1")]
    public partial class AccelerationLimits
    {

        private Xyzlimits translationField;

        private Xyzlimits rotationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public Xyzlimits translation
        {
            get
            {
                return this.translationField;
            }
            set
            {
                this.translationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public Xyzlimits rotation
        {
            get
            {
                return this.rotationField;
            }
            set
            {
                this.rotationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void EnableSpeedProfileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void RestoreDefaultSpeedProfileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void RestoreDefaultPositionLimitsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetSpeedProfileCompletedEventHandler(object sender, GetSpeedProfileCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSpeedProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetSpeedProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public SpeedProfile Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((SpeedProfile)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetAllSpeedProfilesCompletedEventHandler(object sender, GetAllSpeedProfilesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllSpeedProfilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAllSpeedProfilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public SpeedProfile[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((SpeedProfile[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetEnabledSpeedProfileCompletedEventHandler(object sender, GetEnabledSpeedProfileCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEnabledSpeedProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetEnabledSpeedProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public SpeedProfile Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((SpeedProfile)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetAzimuthZeroCompletedEventHandler(object sender, GetAzimuthZeroCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAzimuthZeroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAzimuthZeroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetPositionCompletedEventHandler(object sender, GetPositionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPositionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetPositionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Velocity Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Velocity)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetPositionEventIntervalCompletedEventHandler(object sender, GetPositionEventIntervalCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPositionEventIntervalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetPositionEventIntervalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetPositionLimitsCompletedEventHandler(object sender, GetPositionLimitsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPositionLimitsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetPositionLimitsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public AxisLimits Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((AxisLimits)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetVelocityCompletedEventHandler(object sender, GetVelocityCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVelocityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetVelocityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Velocity Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Velocity)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetVelocityLimitsCompletedEventHandler(object sender, GetVelocityLimitsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVelocityLimitsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetVelocityLimitsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public VelocityLimits Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((VelocityLimits)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetVelocityURLCompletedEventHandler(object sender, GetVelocityURLCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVelocityURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetVelocityURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void InitializePositionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void SetAzimuthZeroCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void SetPositionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void SetPositionEventIntervalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void SetVelocityCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ViewObjectCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}
